MQ/authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import HomeView, MissionView, AddMissionView, BlogSearchView

urlpatterns = [
     path('', views.signin, name="signin"),  # Added trailing slash
    path('missions/<int:pk>', MissionView.as_view(), name='mission-details'),
    path('index/', HomeView.as_view(), name="LandingPage"),
    path('mission_post/', AddMissionView.as_view(), name="add-mission"),
    path('index/', views.BlogSearchView.as_view(), name='search_blogs'),
    path('signup/', views.signup, name="signup"),  # Added trailing slash
    path('signin/', views.signin, name="signin"),  # Added trailing slash
    path('signout/', views.signout, name="signout"),  # Added trailing slash
    path('about/', views.about, name="about"),
    path('contact_us/', views.contact_us, name="contact_us"),
]

MQ/mq/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
] 

MQ/authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Mission(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return f'{self.title} | {self.author.username}'

    def get_absolute_url(self):
        return reverse('mission-details', args=[str(self.pk)])

# class Users(models.Model):
#     profile_pic = models.ImageField(null = True, blank=True, upload_to="static/profiles")

MQ/authentication/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, DetailView, CreateView
from .models import Mission
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class HomeView(ListView):
    model = Mission
    template_name = 'authentication/index.html'

    

class MissionView(DetailView):
    model = Mission 
    template_name = 'authentication/mission_details.html'
    

class AddMissionView(LoginRequiredMixin, CreateView):
    model = Mission
    template_name = 'authentication/mission_post.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogSearchView(ListView):
    model = Mission
    template_name = 'index.html'
    context_object_name = 'missions'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Mission.objects.filter(title__icontains=query).order_by('-created_at')
        else:
            return Mission.objects.none()

def about(request):
    return render(request, "authentication/about.html") 

def contact_us(request):
    return render(request, "authentication/contact_us.html")

def home(request):
    return render(request, "authentication/signin.html")

def signup(request):
    if request.method == "POST":
        username= request.POST['username']
        fname= request.POST['fname']
        lname= request.POST['lname']
        email= request.POST['email']
        pass1= request.POST['pass1']
        pass2= request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request,"Username already exist! Please try some other username")
            return redirect('signin')

        if User.objects.filter(email=email):
            messages.error(request,"Email already registered!")
            return redirect('signin')

        if pass1 != pass2:
            messages.error (request, "Password didn't match!")
            return redirect('signin')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname

        myuser.save()

        messages.success(request, "Your Account has been successfully created")

        return redirect('signin')


    return render(request, "authentication/signup.html")

def signin(request):

    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            login(request, user)
            fname=user.first_name
            return redirect('LandingPage')

        else:
            messages.error(request, "Bad Credentials!")
            return redirect('signin')

    return render(request, "authentication/signin.html")

def signout(request):
    logout(request)
    messages.success(request, "Logged Out Successfully")
    return redirect('signin')

MQ/templates/authentication/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'styleLand.css' %}">

    </head>
    <body>

        <header class="header">

            <nav class="navbar">
                <a href="{% url 'about' %}"><button class= "navbutton">About</button></a>
                <a href="{% url 'LandingPage' %}"><button class= "navbutton">Home</button></a>
                <a href="{% url 'contact_us' %}"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>

  


            <div class="scrollable-square-about">
                <div class="about-title">  <span class="yellow">ABOUT</span> <span class="darkish">MagiQuest</span></div>
                  
                <div class="about-inside">
                    <div class="titles">
                    <span class="yellow">Welcome to</span> <span  class="darkish">MagiQuest!</span>
                        <br>
                </div>
                     <div class="details">
                    <p>At Magiquest, we believe that a lively and dynamic college experience is shaped by the active interaction and the power of community. Our innovative quest system encourages college learners to participate actively in acmpus life by providing enjoyable, fulfilling, and meaningful experiences. </p>
                      </div>

                      <div class="titles"><br>
                        <span class="yellow">How it </span> <span  class="darkish">Works</span>
                         </div>
                         <div class="details">
                            <p>Students can participate in a variety of quests, including helping campus clubs recruit members, organizing study sessions, and engaging in community service projects like campus clean-ups. Completing these quests earns points that can be exchanged for exclusive rewards.</p>
                            <br>
                            <p>Our unique currency system, MagiPoints, rewards your efforts and contributions, which you can use to buy coupons for discounts on snacks, food items in the cafeteria, and university merchandise, as well as unlock exclusive offers. Additionally, MagiQuest features a built-in messaging system to help you connect with fellow students, making it easy to coordinate study sessions, discuss quests, or just have a chat.</p>
                              </div>

                              <br>
                              <div class="titles">
                                <span class="yellow">JOIN US on the Quest </span> <span  class="darkish">for a Better Campus!</span>
                                 </div>

                
                </div>
               
            </div>
            
        </div>
        

        
        

        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/contact_us.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'contact-us.css' %}">
  </head>

  <body background="assets/images/adnu-bg.png" style="background-repeat: no-repeat; background-size: cover;
  background-attachment: center;">
          <header class="header">

            <nav class="navbar">
                <a href="{% url 'about' %}"><button class= "navbutton">About</button></a>
                <a href="{% url 'LandingPage' %}"><button class= "navbutton">Home</button></a>
                <a href="{% url 'contact_us' %}"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>

    <div class="contact-box">
      <div class="contact-header">
        <h1 class="contact-h1">Contact Us</h1>
        <p class="contact-p">Reach out to us for any feedback or concern</p>
      </div>
    </div>

    <div class="container">
      <div class="message-box">
        <form>
          <div class="input-row">
            <div class="input-group">
              <label>Full Name</label>
              <input type="text" placeholder="E.g. Estrella Daanoy M. General">
            </div>
            <div class="input-group">
              <label>Email Address</label>
              <input type="text" placeholder="E.g. magiquest@gmail.com">
            </div>
          </div>
          <div class="input-row">
            <div class="input-group">
              <label>Subject</label>
              <input type="text" placeholder="E.g. Magiquest Feedback">
            </div>
            <div class="input-group">
              <label>Phone</label>
              <input type="text" placeholder="+63 12341231234">
            </div>
          </div>

          <label>Message</label>
          <textarea rows="5" placeholder="Write your message here..."></textarea> 

          <button type="submit" class="submit-button">SUBMIT</button>

        </form>
      </div>
    </div>
  </body>
</html>

MQ/templates/authentication/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Authentication</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        {%for message in messages%}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <strong>Message:</strong>{{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
            </button>   
        </div>
        {%endfor%}

        <h3>Welcome to Magic Quest!</h3>

        {% if user.is_authenticated%}
        <h3>Hello {{ fname }}</h3>
        <h4>You're successfully logged in.</h4>
        <button type="submit"><a href="/signout">Sign out</a></button>

        {%else%}
        <button type="submit"><a href="/signup">Sign up</a></button>
        <button type="submit"><a href="/signin">Sign in</a></button>
      
        {%endif%}
        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/mission_details.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Authentication</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'styleLand.css' %}">

    </head>
    <body>

        <header class="header">

            <nav class="navbar">
                <a href="{% url 'about' %}"><button class= "navbutton">About</button></a>
                <a href="{% url 'LandingPage' %}"><button class= "navbutton">Home</button></a>
                <a href="{% url 'contact_us' %}"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>

        

         <script>
            function showAlert() {
                alert("This function is currently unavailable.");
            }

         </script>
        
        <div class="indContainer">
            <div class="leftCont">
            <img name="logo" id="logo" src="{% static 'images/Title&Logo.png' %}" alt="Logo">
            <div class="profileBox">
                <h3 class="greetings">WELCOME!</h3> <h1 class="greetings" id="greetings_fname">{{ user.first_name }}</h1>
                <!-- <hr name="greetingsLine" id="greetingsLine"> -->
                <div class="magicoin-container">
                    <img src="{% static 'images/magicoin.png' %}" alt="magicoin">
                    <span class="coin-count">69</span>
                </div>
                
                <div class="button-container">
                    <div>
                        <button class="circular-button" type="submit" ><a href="/signout">Sign out</a></button>
                    </div>
                    <div>
                        <button class="circular-button" type="submit" onclick="showAlert()">Profile Logs</button>
                    </div>
                </div>   
            </div>
            </div>
            <div class="mission-desc">
                <div class="mission-container">
                    <div class="mission-left">
                        <strong>POSTED by:</strong><br> {{ mission.author.username }}
                    </div>
                    <div class="mission-right">
                        <div class="mission-title"><h3 >{{ mission.title }}</h3></div>
                      <div  class="mission-body">  {{ mission.body }} </div>
                      <div class="button-whole">
                        <div class="button-left">
                            <a href="{% url 'LandingPage' %}">Back to home</a>
                        </div>

                        
                        <div class="button-right">
                            <a href="#" onclick="showAlert()">Accept Quest</a>
                        </div>
                    </div>
                    
                    </div>
                </div>      
                <ul>
                    {% for mission in object_list %}
                    <li>
                        <a href="{% url 'mission-details' pk=mission.pk %}">
                            <button class="mission-boxes">
                                <div class="username">{{ mission.author.username }}</div>
                                <div class="title">{{ mission.title }}</div>
                            </button>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            
        </div>
        

        
        

        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/mission_post.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Quest Post</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'styleLand.css' %}">

    </head>
    <body>

        <header class="header">

            <nav class="navbar">
                <a href="{% url 'about' %}"><button class= "navbutton">About</button></a>
                <a href="{% url 'LandingPage' %}"><button class= "navbutton">Home</button></a>
                <a href="{% url 'contact_us' %}"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>




         <script>
            function showAlert() {
                alert("This function is currently unavailable.");
            }

         </script>
        
        <div class="indContainer">
            <div class="leftCont">
            <img name="logo" id="logo" src="{% static 'images/Title&Logo.png' %}" alt="Logo">
            <div class="profileBox">
                <h3 class="greetings">WELCOME!</h3> <h1 class="greetings" id="greetings_fname">{{ user.first_name }}</h1>
                <!-- <hr name="greetingsLine" id="greetingsLine"> -->
                <div class="magicoin-container">
                    <img src="{% static 'images/magicoin.png' %}" alt="magicoin">
                    <span class="coin-count">69</span>
                </div>
                
                <div class="button-container">
                    <div>
                        <button class="circular-button" type="submit" ><a href="/signout">Sign out</a></button>
                    </div>
                    <div>
                        <button class="circular-button" type="submit" onclick="showAlert()">Profile Logs</button>
                    </div>
                </div>   
            </div>
            </div>
            <div class="mission-desc">
                <div class="mission-container">
                
                        <form method="POST" class="post-form">
                            {% csrf_token %}
                            <div class="form-group">
                     
                                <!-- Apply unique class or ID to the title text area -->
                                <div class="quest-container">
                                    <span class="quest-title">Quest Title</span>
                                    <textarea name="title" id="id_title" class="form-input title-textarea"></textarea>
                                </div>
                                
                            </div>
                            <div class="form-group">
                                <textarea name="body" id="id_body" class="form-input"></textarea>
                            </div>

                            <div class="button-container">
                                <div class="left-button">
                                    <a href="{% url 'LandingPage' %}"><span id="cancel">Cancel</span></a>
                                </div>
                                <div class="right-button">
                                    <button type="submit" class="post-button right-button" href="{% url 'LandingPage' %}">Submit</button>
                                </div>
                            </div>
                            
                        </form>

                        </div>
                    
                    </div>
                </div>      
                <ul>
                    {% for mission in object_list %}
                    <li>
                        <a href="{% url 'mission-details' pk=mission.pk %}">
                            <button class="mission-boxes">
                                <div class="username">{{ mission.author.username }}</div>
                                <div class="title">{{ mission.title }}</div>
                            </button>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            
        </div>
        

        
        

        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/profile.html
        
        {% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
       
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    </head>
    <body>

        <header class="header">

            <nav class="navbar">
                <a href="#"><button class= "navbutton">About</button></a>
                <a href="#"><button class= "navbutton">Home</button></a>
                <a href="#"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>

            
        <section class="logo-and-forms">
            <div class="logo">
                <img name="logo" id="logo" src="{% static 'images/Title&Logo.png' %}" alt="Logo">
            </div>
        
            <div class="form-container">
                <form action="/signin/" method="post">
                    <h3 class="formtitle">LOGIN</h3>
                    {% csrf_token %}
                    <label for="Username" class="infolabel">Username</label>
                    <input type="text" id="username" name="username" class="formbox" placeholder="Enter your Username" required>
                    <br>
                    <label for="Username"  class="infolabel">Password</label>
                    <input type="password" id="pass1" name="pass1" class="formbox" placeholder="Enter your password" required>
                    <br>
                  
                    <button type="submit" class="loginbutton">Login</button>
                    <button type="button" class="registerbutton" onclick="redirectToRegister()">Register here!</button>
                        <!-- redirect to register -->
                        <script>
                            function redirectToRegister() {
                                window.location.href = "/signup"; 
                            }
                        </script>

                </form>
            </div>
        </section>

        <footer><p>© 2024 | MagiQuest by Ateneo De Naga University Students | All Rights Reserved</p></footer>
        
       
       


       
        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/signin.html
        
        {% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" conten   t="IE=edge">
        <title>Login page</title>
       
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    </head>
    <body>

        <header class="header">

            <nav class="navbar">
                <a href="#"><button class= "navbutton">About</button></a>
                <a href="#"><button class= "navbutton">Home</button></a>
                <a href="#"><button class= "navbutton">Contact us</button></a>
        </nav>

        </header>

            
        <section class="logo-and-forms">
            <div class="logo">
                <img name="logo" id="logo" src="{% static 'images/Title&Logo.png' %}" alt="Logo">
            </div>
        
            <div class="form-container">
                <form action="/signin/" method="post">
                    <h3 class="formtitle">LOGIN</h3>
                    {% csrf_token %}
                    <label for="Username" class="infolabel">Username</label>
                    <input type="text" id="username" name="username" class="formbox" placeholder="Enter your Username" required>
                    <br>
                    <label for="Username"  class="infolabel">Password</label>
                    <input type="password" id="pass1" name="pass1" class="formbox" placeholder="Enter your password" required>
                    <br>
                  
                    <button type="submit" class="loginbutton">Login</button>
                    <button type="button" class="registerbutton" onclick="redirectToRegister()">Register here!</button>
                        <!-- redirect to register -->
                        <script>
                            function redirectToRegister() {
                                window.location.href = "/signup"; 
                            }
                        </script>

                </form>
            </div>
        </section>

        <footer><p>© 2024 | MagiQuest by Ateneo De Naga University Students | All Rights Reserved</p></footer>
        
       
       


       
        <script src="" async defer></script>
    </body>
</html>

MQ/templates/authentication/signup.html
        
        {% load static %}
        <!DOCTYPE html>

        <html>
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" conten   t="IE=edge">
                <title>Register page</title>
               
                <meta name="description" content="">
                <meta name="viewport" content="width=device-width, initial-scale=1">
        
                <link rel="stylesheet" type="text/css" href="{% static 'styleReg.css' %}">
        
            </head>
            <body>
                <script>
                    function LoginAlert() {
                        alert("You must login first!.");
                    }
            
                 </script>
        
                <header class="header">

                    <nav class="navbar">
                        <a href="{% url 'about' %}"><button class= "navbutton">About</button></a>
                        <a href="#"><button class= "navbutton" onclick="LoginAlert()">Home</button></a>
                        <a href="{% url 'contact_us' %}"><button class= "navbutton">Contact us</button></a>
                </nav>
        
        
        
                </header>
        
        
                    
                <section class="logo-and-forms">
                    <div class="logo">
                        <img name="logo" id="logo" src="{% static 'images/Title&Logo.png' %}" alt="Logo">
                    </div>
                
                    <div class="form-container" id="fcRegister" name="fcRegister">
                        <form action="/signup/" method="post">
                            <h3 class="formtitle">REGISTER</h3>
                            {% csrf_token %}
                            <label for="Username" class="infolabel">Username</label>
                            <input type="text" id="username" name="username" class="formbox" placeholder="Enter your Username" required>
                            <br>
                            <label for="fname" class="infolabel">First Name</label>
                            <input type="text" id="fname" name="fname" class="formbox" placeholder="Enter your First Name" required>
                            <br>
                            <label for="lname" class="infolabel" id="lnameLabel">Last Name (optional)</label>
                            <input type="text" id="lname" name="lname" class="formbox" placeholder="Enter your Last Name" >
                            <br>
                            <label for="email" class="infolabel" id="emailAdd" name="emailAdd" >Email Address</label>
                            <input type="email" id="email" name="email" class="formbox" placeholder="Enter Your Email" required>
                            <br>                    

                            <label for="password"  class="infolabel">Password</label>
                            <input type="password" id="pass1" name="pass1" class="formbox" placeholder="Enter your password" required>
                            <br>
                             <label for="password"  class="infolabel" id="Cpass" name="Cpass">Confirm Password</label>
                            <input type="password" id="pass2" name="pass2" class="formbox" placeholder="Enter your password" required>
                            <br>
                          
                            <button type="submit" class="loginbutton">Register</button>
                            <button type="button" class="registerbutton" onclick="redirectToRegister()">Login Here!</button>
                                <!-- redirect to register -->
                                <script>
                                    function redirectToRegister() {
                                        window.location.href = "/signin"; 
                                    }
                                </script>
        
                        </form>
                    </div>
                </section>
        
                <footer><p>© 2024 | MagiQuest by Ateneo De Naga University Students | All Rights Reserved</p></footer>
                
               
               
        
        
               
                <script src="" async defer></script>
            </body>
        </html>